version: "3.9"  # optional since v1.27.0
services:
  monitor:
    image: citusdata/pg_auto_failover
    environment:
      PGDATA: /tmp/pgaf
    command: pg_autoctl create monitor --ssl-self-signed --auth trust --run
    ports:
      - "5500:5432"
    networks:
      vlan:
        ipv4_address: 172.54.32.100
  node1:
    image: citusdata/pg_auto_failover
    environment:
      PGDATA: /tmp/pgaf
    command: [
    "pg_autoctl", "create", "postgres",
    "--ssl-self-signed",
    "--auth", "trust",
    #"--hostname", "node1",
    "--hostname", "172.54.32.101",
    "--username", "ad",
    "--dbname", "analytics",
    "--monitor", "postgresql://autoctl_node@monitor/pg_auto_failover",
    "--run"]
    ports:
      - "5501:5432"
    networks:
      vlan:
        ipv4_address: 172.54.32.101
  node2:
    image: citusdata/pg_auto_failover
    ports:
      - "5432:5432"
    environment:
      PGDATA: /tmp/pgaf
    command: [
    "pg_autoctl", "create", "postgres",
    "--ssl-self-signed",
    "--auth", "trust",
    #"--hostname", "node2",
    "--hostname", "172.54.32.102",
    "--username", "ad",
    "--dbname", "analytics",
    "--monitor", "postgresql://autoctl_node@monitor/pg_auto_failover",
    "--run"]
    ports:
      - "5502:5432"
    networks:
      vlan:
        ipv4_address: 172.54.32.102
  node3:
    image: citusdata/pg_auto_failover
    environment:
      PGDATA: /tmp/pgaf
    command: [
    "pg_autoctl", "create", "postgres",
    "--ssl-self-signed",
    "--auth", "trust",
    #"--hostname", "node3",
    "--hostname", "172.54.32.103",
    "--username", "ad",
    "--dbname", "analytics",
    "--monitor", "postgresql://autoctl_node@monitor/pg_auto_failover",
    "--run"]
    ports:
      - "5503:5432"
    networks:
      vlan:
        ipv4_address: 172.54.32.103
  web:
    build: .
    ports:
      - "8080:8080"
    command: make runserver
networks:
  vlan:
    ipam:
      config:
        - subnet: 172.54.32.0/24
